version: '3.8'

services:
  shift_postgres:
    build:
      context: infra/postgres
      dockerfile: Dockerfile
    container_name: shift_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - shift_network

networks:
  shift_network: {}
# volumes:
#   postgres-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./infra/postgres/data
